image: wisetc/cnode:8

# 定义 stages
stages:
  - install
  - build
  
cache:
  key: "$CI_JOB_NAME"
  paths:
    - node_modules/

  # 定义 job
install:
  stage: install
  only:
    - master
  script:
    - node -v
    - npm install -g cnpm --registry=https://registry.npm.taobao.org
    - cnpm -v
    - cnpm install
  tags:
    - vue
    
# 定义 job
build:
  stage: build
  only:
    - master
  script:
    - ls -lh /dev/m-tigerprawn-hand
    - npm run build
    - ls -lh m-tigerprawn-hand
    - cp -r m-tigerprawn-hand/* /dev/m-tigerprawn-hand
  tags:
    - vue
    


