image: node:12

before_script:
  - echo "$SSH_PRIVATE_KEY"
  - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
  - eval $(ssh-agent -s)
  - ssh-add <(echo "$SSH_PRIVATE_KEY")
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh
  - '[[ -f /.dockerinit ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'

# 定义 stages
stages:
  - build
  
cache:
  key: "$CI_JOB_NAME"
  paths:
    - node_modules/

    
# 定义 job
build:
  stage: build
  only:
    - master
  script:
    - node -v
    - npm install -g cnpm --registry=https://registry.npm.taobao.org
    - cnpm -v
    - cnpm install
    - npm run build
    - ls 
    - scp -r m-tigerprawn-hand lxz@192.168.63.200:/home/lxz/sl/deploy/childApp/
  tags:
    - vue
    


