/**
 * 应急响应
 * unknown
 *
 * OpenAPI spec version: last
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

/**
  * @property `[statusCode]` 状态码
  * @property `[message]` 状态描述
  * @property `[data]` 
  */
export interface Add {
  /**
   * 状态码
   */
  "statusCode"?: number;
  /**
   * 状态描述
   */
  "message"?: string;
  "data"?: models.AddData;
}

