/**
 * 应急响应
 * unknown
 *
 * OpenAPI spec version: last
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

/**
  * @description 数据
  * @property `[id]` 应急响应唯一标识
  */
export interface AddData {
  /**
   * 应急响应唯一标识
   */
  "id"?: number;
}

