/**
 * 应急响应
 * unknown
 *
 * OpenAPI spec version: last
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

/**
  * @property `[data]` 
  * @property `[count]` 
  */
export interface ListData {
  "data"?: Array<models.ListDataData>;
  "count"?: number;
}

